package com.jdp.hls.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jdp.hls.greendaobean.Area;
import com.jdp.hls.greendaobean.TDict;

import com.jdp.hls.dao.AreaDao;
import com.jdp.hls.dao.TDictDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig areaDaoConfig;
    private final DaoConfig tDictDaoConfig;

    private final AreaDao areaDao;
    private final TDictDao tDictDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        areaDaoConfig = daoConfigMap.get(AreaDao.class).clone();
        areaDaoConfig.initIdentityScope(type);

        tDictDaoConfig = daoConfigMap.get(TDictDao.class).clone();
        tDictDaoConfig.initIdentityScope(type);

        areaDao = new AreaDao(areaDaoConfig, this);
        tDictDao = new TDictDao(tDictDaoConfig, this);

        registerDao(Area.class, areaDao);
        registerDao(TDict.class, tDictDao);
    }
    
    public void clear() {
        areaDaoConfig.clearIdentityScope();
        tDictDaoConfig.clearIdentityScope();
    }

    public AreaDao getAreaDao() {
        return areaDao;
    }

    public TDictDao getTDictDao() {
        return tDictDao;
    }

}
